---
- name: Set up new Minecraft game
  hosts: localhost

  tasks:
    - name: Check for environment variables
      fail:
        msg: 'A required environment variable is not set'
      when: 'item == ""'
      loop:
        - '{{ lookup("env", "LEVEL_NAME") }}'
        - '{{ lookup("env", "SERVER_PORT") }}'

    - set_fact:
        level_name: '{{ lookup("env", "LEVEL_NAME") }}'
        server_port: '{{ lookup("env", "SERVER_PORT") }}'
        data_path: '/root/bedrock/{{ lookup("env", "LEVEL_NAME") }}'
        world_path: '/root/bedrock/{{ lookup("env", "LEVEL_NAME") }}/worlds/{{ lookup("env", "LEVEL_NAME") }}'

    - name: stop old container if it exists
      docker_container:
        name: bedrock-{{ level_name }}
        state: absent

    - name: create game directories
      file:
        path: '{{ item.path }}'
        group: teamcity
        mode: '{{ item.mode }}'
        state: directory
      become: yes
      loop:
        - { path: '/root/bedrock', mode: g+ws }
        - { path: '/root/bedrock/{{ level_name }}', mode: g+w }
        - { path: '/root/bedrock/{{ level_name }}/worlds', mode: g+w }

    - name: check for game save
      stat:
        path: '{{ world_path }}'
      register: world_save
      become: yes

    - name: backup world
      shell:
        cmd: '(cd {{ world_path }} && zip -r - *) > {{ level_name }}.mcworld'
      become: yes
      when: world_save.stat.exists

    - name: write/update server.properties
      template:
        src: server.properties
        dest: /root/bedrock/{{ level_name }}/server.properties
        group: teamcity
        mode: g+w
      become: yes

    - name: start container
      docker_container:
        name: bedrock-{{ level_name }}
        image: bedrock-server
        auto_remove: yes
        detach: yes
        interactive: yes
        tty: yes
        published_ports:
          - "{{ server_port }}:19132/udp"
        volumes:
          - '{{ data_path }}:/bedrock-server/docker'
        state: started
      when: 'lookup("env", "PREVENT_RESTART") == true'
